version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
       container_name: flight-booking-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      JWT_SECRET: your-secret-key
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./user
      dockerfile: Dockerfile
       container_name: flight-booking-frontend
    ports:
      - "3000:3000"
    environment:
      APP_API_URL: http://backend:5000
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
